# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ehci_pci" "xhci_pci_renesas" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "thinkpad_acpi"];
  boot.extraModulePackages = [];
  boot.kernelPackages = pkgs.linuxPackages_zen;

  powerManagement.cpuFreqGovernor = "performance";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/505fe06c-d1b8-4499-ae30-d25cc7a3592b";
    fsType = "btrfs";
    options = ["subvol=@" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/505fe06c-d1b8-4499-ae30-d25cc7a3592b";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/505fe06c-d1b8-4499-ae30-d25cc7a3592b";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0792-2D09";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.bluetooth.enable = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
